import pyautogui

pyautogui.press('Win')
pyautogui.sleep(1)
pyautogui.write('Microsoft edg', interval= 0.2)
pyautogui.press('Enter')
pyautogui.sleep(2)
pyautogui.hotkey('Alt', 'd')
pyautogui.press('Enter')
pyautogui.write('instagram.com')
pyautogui.sleep(1)
pyautogui.press('Enter')
pyautogui.sleep(2)
pyautogui.press('Tab')
pyautogui.sleep(2)
pyautogui.write('@m_moraiisz')
pyautogui.sleep(2)
pyautogui.press('Tab')
pyautogui.write('password')
pyautogui.sleep(1)
pyautogui.press('Tab')
pyautogui.press('Tab')
pyautogui.press('Enter')
pyautogui.sleep(30)
pyautogui.hotkey('Alt', 'F4')