import pyautogui

pyautogui.press('Win')
pyautogui.sleep(1)
pyautogui.write('Google Chrome', interval= 0.2)
pyautogui.press('Enter')
pyautogui.sleep(2)
pyautogui.write('Senai - Santana de Parnaíba', interval= 0.9)
pyautogui.press('Enter')
pyautogui.sleep(1)
pyautogui.moveTo(906, 507, duration= 0.4)
pyautogui.click()
pyautogui.sleep(1)
pyautogui.hotkey('Shift', 'Win', 'S')
pyautogui.sleep(1)
pyautogui.moveTo(811, 226, duration= 0.5)

pyautogui.mouseDown()
pyautogui.moveTo(1751, 1025, duration= 0.5)
pyautogui.mouseUp()
pyautogui.sleep(2)
pyautogui.press('Win')
pyautogui.sleep(1)
pyautogui.write('Pain', interval= 0.2)
pyautogui.press('Enter')
pyautogui.sleep(2)
pyautogui.hotkey('Ctrl', 'V')